// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWMeTAqT6iZaAab-uK-DSLxE_7MHc7_Cs',
    appId: '1:548420805481:web:cc4cff8da9f6f927c253f8',
    messagingSenderId: '548420805481',
    projectId: 'flutter-chat-app-1caa6',
    authDomain: 'flutter-chat-app-1caa6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1caa6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7TPI5dyzx7cjpU9eyRCaiTsoCQIobHDw',
    appId: '1:548420805481:android:58ceaf427fbce787c253f8',
    messagingSenderId: '548420805481',
    projectId: 'flutter-chat-app-1caa6',
    storageBucket: 'flutter-chat-app-1caa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQy2InCUa3CG_cLlZL_0WhoEQANMptBes',
    appId: '1:548420805481:ios:0ff8a43cf2573f65c253f8',
    messagingSenderId: '548420805481',
    projectId: 'flutter-chat-app-1caa6',
    storageBucket: 'flutter-chat-app-1caa6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQy2InCUa3CG_cLlZL_0WhoEQANMptBes',
    appId: '1:548420805481:ios:0ff8a43cf2573f65c253f8',
    messagingSenderId: '548420805481',
    projectId: 'flutter-chat-app-1caa6',
    storageBucket: 'flutter-chat-app-1caa6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWMeTAqT6iZaAab-uK-DSLxE_7MHc7_Cs',
    appId: '1:548420805481:web:6d57c6459b2c2ceac253f8',
    messagingSenderId: '548420805481',
    projectId: 'flutter-chat-app-1caa6',
    authDomain: 'flutter-chat-app-1caa6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1caa6.firebasestorage.app',
  );

}